[package]
name = "frankmer"
version = "0.1.0"
authors = ["jamesinlow"]
edition = "2018"

[features]
mac-notification = ["dep:mac-notification-sys"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.18.2"
figlet-rs = "0.1.3"
clap = "2.3.3"
regex= "1"
mac-notification-sys = {version = "0.5.6", optional = true }